# Site settings
title: Paikblog
email: paikwiki@gmail.com
description: "Geek with the keys."
baseurl: ""
url: "http://paikwik.github.io"
twitter_username: ch_paik
github_username:  paikwiki

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jemoji